In [1]:
import pandas as pd

# Create a sample DataFrame with inconsistent category spellings
data = {
    'category': ['Furniture', 'furnture', 'Furnitures', 'Electronics', 'Electronics ', 'books', 'Books'],
    'value': [10, 20, 15, 30, 25, 5, 8]
}
df_categories = pd.DataFrame(data)

print("Original DataFrame:")
display(df_categories)

print("\nGrouping before cleaning (shows inconsistent results):")
display(df_categories.groupby('category')['value'].sum().reset_index())

Original DataFrame:

       category  value
0     Furniture     10
1      furnture     20
2    Furnitures     15
3   Electronics     30
4  Electronics      25
5         books      5
6         Books      8

Grouping before cleaning (shows inconsistent results):

       category  value
0         Books      8
1   Electronics     30
2  Electronics      25
3     Furniture     10
4    Furnitures     15
5         books      5
6      furnture     20

In [2]:
# Define a function to clean and normalize category names
def clean_category(category_name):
    if pd.isna(category_name): # Handle potential NaN values
        return category_name
    category_name = str(category_name).strip().lower() # Convert to lowercase and strip whitespace

    # Map common variations to a standardized name
    if category_name in ['furnitures', 'furnture', 'funiture']:
        return 'furniture'
    elif category_name in ['electronics', 'electronic']:
        return 'electronics'
    elif category_name in ['books', 'book']:
        return 'books'
    else:
        return category_name # Return as is if no specific mapping is found

# Apply the cleaning function to the 'category' column
df_categories['cleaned_category'] = df_categories['category'].apply(clean_category)

print("DataFrame after adding cleaned category column:")
display(df_categories)

DataFrame after adding cleaned category column:

       category  value cleaned_category
0     Furniture     10        furniture
1      furnture     20        furniture
2    Furnitures     15        furniture
3   Electronics     30      electronics
4  Electronics      25      electronics
5         books      5            books
6         Books      8            books

In [3]:
print("Grouping after cleaning (shows correct results):")
display(df_categories.groupby('cleaned_category')['value'].sum().reset_index())

Grouping after cleaning (shows correct results):

  cleaned_category  value
0            books     13
1      electronics     55
2        furniture     45