In [1]:
#Task 1

import pandas as pd

# Define the file path
file_path = '/content/Global Superstore Orders 2016.xlsx'

# Load the dataset
df = pd.read_excel(file_path)

# Display the number of rows and columns
print("Shape of the dataset (rows, columns):")
print(df.shape)

# List all column names
print("\nColumn names:")
print(df.columns.tolist())

# Show the first five rows
print("\nFirst five rows of the dataset:")
display(df.head())

Shape of the dataset (rows, columns):
(51292, 28)

Column names:
['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Postal Code', 'City', 'State', 'Country', 'Region', 'Market', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Unnamed: 18', 'Sales', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Quantity', 'Discount', 'Profit', 'Shipping Cost', 'Order Priority']

First five rows of the dataset:

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Unnamed: 18,Sales,Unnamed: 20,Unnamed: 21,Unnamed: 22,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,NaN,NaN,70.00,100.0,70.00,2.0,0.0,62.1544,40.77,High
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,...,NaN,NaN,80.00,100.0,80.00,9.0,0.1,-288.7650,923.63,Critical
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,NaN,Brisbane,...,NaN,NaN,99.00,100.0,99.00,9.0,0.1,919.9710,915.49,Medium
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,NaN,Berlin,...,NaN,NaN,90.00,100.0,90.00,5.0,0.1,-96.5400,910.16,Medium
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,NaN,Dakar,...,NaN,NaN,25.25,100.0,25.25,8.0,0.0,311.5200,903.04,Critical

In [3]:
#Task 2

# Display summary statistics for numerical columns, including Sales and Profit
print("\nSummary Statistics:")
display(df[['Sales', 'Profit']].describe().round(2))

Summary Statistics:

          Sales    Profit
count  51279.00  51290.00
mean     245.96     28.61
std      485.54    174.34
min        0.00  -6599.98
25%       30.74      0.00
50%       85.05      9.24
75%      250.99     36.81
max    22638.48   8399.98

In [7]:
#Task 3

# Filter and display rows where Sales are greater than 500
sales_gt_500 = df[df['Sales'] > 500]
print("\nRows where Sales > 500:")
display(sales_gt_500.head())
print(f"Number of rows where Sales > 500: {sales_gt_500.shape[0]}")
print('\n')

# Change the filter value to 1000 and compare the number of rows
sales_gt_1000 = df[df['Sales'] > 1000]
print("\nRows where Sales > 1000:")
display(sales_gt_1000.head())
print(f"Number of rows where Sales > 1000: {sales_gt_1000.shape[0]}")

Rows where Sales > 500:

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Unnamed: 18,Sales,Unnamed: 20,Unnamed: 21,Unnamed: 22,Quantity,Discount,Profit,Shipping Cost,Order Priority
14,45794,ES-2015-PO18865139-42018,2015-01-14,2015-01-18,Standard Class,PO-18865139,Patrick O'Donnell,Consumer,NaN,Stockton-on-Tees,...,NaN,2616.960,NaN,NaN,NaN,4.0,0.0,1151.400,832.41,Critical
15,4132,IN-2012-DL128657-40918,2012-01-10,2012-01-11,First Class,DL-128657,Dan Lawera,Consumer,NaN,Brisbane,...,NaN,2221.800,NaN,NaN,NaN,7.0,0.0,622.020,810.25,Critical
16,27704,ID-2014-JB1600059-41873,2014-08-22,2014-08-26,Standard Class,JB-1600059,Joy Bell-,Consumer,NaN,Mataram,...,NaN,3701.520,NaN,NaN,NaN,12.0,0.0,1036.080,804.54,Critical
17,13779,IN-2015-BF1100558-42319,2015-11-11,2015-11-15,Standard Class,BF-1100558,Barry Franz,Home Office,NaN,Gorakhpur,...,NaN,1869.588,NaN,NaN,NaN,4.0,0.1,186.948,801.66,Critical
19,12069,CA-2013-AH10030140-41635,2013-12-27,2013-12-31,Standard Class,AH-100301404,Aaron Hawkins,Corporate,94122.0,San Francisco,...,NaN,7958.580,NaN,NaN,NaN,14.0,0.0,3979.080,778.32,Low

Number of rows where Sales > 500: 6744



Rows where Sales > 1000:

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Unnamed: 18,Sales,Unnamed: 20,Unnamed: 21,Unnamed: 22,Quantity,Discount,Profit,Shipping Cost,Order Priority
14,45794,ES-2015-PO18865139-42018,2015-01-14,2015-01-18,Standard Class,PO-18865139,Patrick O'Donnell,Consumer,NaN,Stockton-on-Tees,...,NaN,2616.960,NaN,NaN,NaN,4.0,0.0,1151.400,832.41,Critical
15,4132,IN-2012-DL128657-40918,2012-01-10,2012-01-11,First Class,DL-128657,Dan Lawera,Consumer,NaN,Brisbane,...,NaN,2221.800,NaN,NaN,NaN,7.0,0.0,622.020,810.25,Critical
16,27704,ID-2014-JB1600059-41873,2014-08-22,2014-08-26,Standard Class,JB-1600059,Joy Bell-,Consumer,NaN,Mataram,...,NaN,3701.520,NaN,NaN,NaN,12.0,0.0,1036.080,804.54,Critical
17,13779,IN-2015-BF1100558-42319,2015-11-11,2015-11-15,Standard Class,BF-1100558,Barry Franz,Home Office,NaN,Gorakhpur,...,NaN,1869.588,NaN,NaN,NaN,4.0,0.1,186.948,801.66,Critical
19,12069,CA-2013-AH10030140-41635,2013-12-27,2013-12-31,Standard Class,AH-100301404,Aaron Hawkins,Corporate,94122.0,San Francisco,...,NaN,7958.580,NaN,NaN,NaN,14.0,0.0,3979.080,778.32,Low

Number of rows where Sales > 1000: 2618

In [11]:
# Task 4

# Sort orders by Profit from highest to lowest
df_sorted_by_profit = df.sort_values(by='Profit', ascending=False)

# Display the top five rows after sorting
print("\nTop five orders by Profit (highest to lowest):")
display(df_sorted_by_profit.head())

Top five orders by Profit (highest to lowest):

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Unnamed: 18,Sales,Unnamed: 20,Unnamed: 21,Unnamed: 22,Quantity,Discount,Profit,Shipping Cost,Order Priority
49005,38123,CA-2014-TC20980140-41915,2014-10-03,2014-10-10,Standard Class,TC-209801402,Tamara Chand,Corporate,47905.0,Lafayette,...,NaN,17499.95,NaN,NaN,NaN,5.0,0.0,8399.9760,349.07000,Medium
44250,39450,CA-2015-RB19360140-42087,2015-03-24,2015-03-26,First Class,RB-193601404,Raymond Buch,Consumer,98115.0,Seattle,...,NaN,13999.96,NaN,NaN,NaN,4.0,0.0,6719.9808,20.00054,Medium
25240,35487,CA-2015-HL15040140-42326,2015-11-18,2015-11-23,Standard Class,HL-150401406,Hunter Lopez,Consumer,19711.0,Newark,...,NaN,10499.97,NaN,NaN,NaN,3.0,0.0,5039.9856,363.19000,Medium
421,40336,CA-2014-AB10105140-41991,2014-12-18,2014-12-22,Standard Class,AB-101051402,Adrian Barton,Consumer,48205.0,Detroit,...,NaN,9892.74,NaN,NaN,NaN,13.0,0.0,4946.3700,498.70000,Medium
46297,35395,CA-2012-SC20095140-41174,2012-09-22,2012-09-27,Standard Class,SC-200951402,Sanjit Chand,Consumer,55407.0,Minneapolis,...,NaN,9449.95,NaN,NaN,NaN,5.0,0.0,4630.4755,655.61000,Medium

In [32]:
#Task 5

# Group by Category and calculate total Profit
profit_by_category = df.groupby('Category')['Profit'].sum()
print("Total Profit by Category:")
display(profit_by_category)


# Group by Market and calculate total Profit
profit_by_market = df.groupby('Market')['Profit'].sum()
print("\nTotal Profit by Market:")
display(profit_by_market)

Total Profit by Category:

Category
Furniture          285082.73020
Office Supplies    518595.82790
Technology         663778.73318
Name: Profit, dtype: float64

Total Profit by Market:

Market
Africa           88871.63100
Asia Pacific    403176.03800
Europe          449551.72350
LATAM           221643.48708
USCA            304214.41170
Name: Profit, dtype: float64

In [33]:
#Task 6

# Add a new column 'Profit_Per_Sale'
df['Profit_Per_Sale'] = df['Profit'] / df['Sales']
print("\nFirst five rows of the DataFrame with 'Profit_Per_Sale' column:")
display(df.head(25))

First five rows of the DataFrame with 'Profit_Per_Sale' column:

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Sales,Unnamed: 20,Unnamed: 21,Unnamed: 22,Quantity,Discount,Profit,Shipping Cost,Order Priority,Profit_Per_Sale
0,40098,CA-2014-AB10015140-41954,2014-11-11,2014-11-13,First Class,AB-100151402,Aaron Bergman,Consumer,73120.0,Oklahoma City,...,NaN,70.00,100.0,70.00,2.0,0.0,62.1544,40.77,High,NaN
1,26341,IN-2014-JR162107-41675,2014-02-05,2014-02-07,Second Class,JR-162107,Justin Ritter,Corporate,NaN,Wollongong,...,NaN,80.00,100.0,80.00,9.0,0.1,-288.7650,923.63,Critical,NaN
2,25330,IN-2014-CR127307-41929,2014-10-17,2014-10-18,First Class,CR-127307,Craig Reiter,Consumer,NaN,Brisbane,...,NaN,99.00,100.0,99.00,9.0,0.1,919.9710,915.49,Medium,NaN
3,13524,ES-2014-KM1637548-41667,2014-01-28,2014-01-30,First Class,KM-1637548,Katherine Murray,Home Office,NaN,Berlin,...,NaN,90.00,100.0,90.00,5.0,0.1,-96.5400,910.16,Medium,NaN
4,47221,SG-2014-RH9495111-41948,2014-11-05,2014-11-06,Same Day,RH-9495111,Rick Hansen,Consumer,NaN,Dakar,...,NaN,25.25,100.0,25.25,8.0,0.0,311.5200,903.04,Critical,NaN
5,1962-03-27 00:00:00,ES-2013-BS1136545-41472,2013-07-17,2013-07-19,First Class,BS-1136545,Bill Shonely,Corporate,NaN,Saint-Brieuc,...,NaN,72.85,NaN,NaN,5.0,0.1,763.2750,897.35,Critical,NaN
6,30570,CA-2013-AH10030140-41635,2013-12-27,2013-12-31,Standard Class,AH-100301404,Aaron Hawkins,Corporate,94122.0,San Francisco,...,NaN,NaN,NaN,NaN,4.0,0.0,564.8400,894.77,Critical,NaN
7,31192,IN-2012-DP131057-41215,2012-11-02,2012-11-04,Second Class,DP-131057,Dave Poirier,Corporate,NaN,Gold Coast,...,NaN,NaN,NaN,NaN,6.0,0.0,996.4800,878.38,High,NaN
8,40099,CA-2013-AH10030140-41635,2013-12-27,2013-12-31,Standard Class,AH-100301404,Aaron Hawkins,Corporate,94122.0,San Francisco,...,NaN,NaN,NaN,NaN,2.0,0.0,54.7136,25.27,High,NaN
9,36258,CG-2012-AH1003033-41165,2012-09-13,2012-09-14,First Class,AH-1003033,Aaron Hawkins,Corporate,NaN,Kamina,...,NaN,NaN,NaN,NaN,1.0,0.2,5.4801,11.13,High,NaN
10,36259,CA-2012-AH10030140-41041,2012-05-12,2012-05-18,Standard Class,AH-100301404,Aaron Hawkins,Corporate,90004.0,Los Angeles,...,NaN,NaN,NaN,NaN,3.0,0.0,4.6644,4.29,High,NaN
11,28879,CA-2012-AH10030140-41273,2012-12-30,2012-12-31,First Class,AH-100301406,Aaron Hawkins,Corporate,10035.0,New York City,...,NaN,NaN,NaN,NaN,5.0,0.0,647.5500,835.57,High,NaN
12,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,45794,ES-2015-PO18865139-42018,2015-01-14,2015-01-18,Standard Class,PO-18865139,Patrick O'Donnell,Consumer,NaN,Stockton-on-Tees,...,2616.960,NaN,NaN,NaN,4.0,0.0,1151.4000,832.41,Critical,0.439976
15,4132,IN-2012-DL128657-40918,2012-01-10,2012-01-11,First Class,DL-128657,Dan Lawera,Consumer,NaN,Brisbane,...,2221.800,NaN,NaN,NaN,7.0,0.0,622.0200,810.25,Critical,0.279962
16,27704,ID-2014-JB1600059-41873,2014-08-22,2014-08-26,Standard Class,JB-1600059,Joy Bell-,Consumer,NaN,Mataram,...,3701.520,NaN,NaN,NaN,12.0,0.0,1036.0800,804.54,Critical,0.279907
17,13779,IN-2015-BF1100558-42319,2015-11-11,2015-11-15,Standard Class,BF-1100558,Barry Franz,Home Office,NaN,Gorakhpur,...,1869.588,NaN,NaN,NaN,4.0,0.1,186.9480,801.66,Critical,0.099994
18,39519,ES-2013-BS1136545-41472,2013-07-17,2013-07-19,First Class,BS-1136545,Bill Shonely,Corporate,NaN,Saint-Brieuc,...,12.624,NaN,NaN,NaN,2.0,0.2,-2.5248,1.97,Low,-0.200000
19,12069,CA-2013-AH10030140-41635,2013-12-27,2013-12-31,Standard Class,AH-100301404,Aaron Hawkins,Corporate,94122.0,San Francisco,...,7958.580,NaN,NaN,NaN,14.0,0.0,3979.0800,778.32,Low,0.499974
20,22096,IN-2012-DP131057-41215,2012-11-02,2012-11-04,Second Class,DP-131057,Dave Poirier,Corporate,NaN,Gold Coast,...,2565.594,NaN,NaN,NaN,9.0,0.1,28.4040,766.93,Critical,0.011071
21,49463,CA-2013-AH10030140-41635,2013-12-27,2013-12-31,Standard Class,AH-100301404,Aaron Hawkins,Corporate,94122.0,San Francisco,...,3409.740,NaN,NaN,NaN,6.0,0.0,818.2800,763.38,High,0.239983
22,46630,CG-2012-AH1003033-41165,2012-09-13,2012-09-14,First Class,AH-1003033,Aaron Hawkins,Corporate,NaN,Kamina,...,1977.720,NaN,NaN,NaN,4.0,0.0,276.8400,759.47,Critical,0.139979
23,36260,CA-2012-AH10030140-41041,2012-05-12,2012-05-18,Standard Class,AH-100301404,Aaron Hawkins,Corporate,90004.0,Los Angeles,...,242.940,NaN,NaN,NaN,3.0,0.0,4.8588,1.28,High,0.020000
24,21586,CA-2012-AH10030140-41273,2012-12-30,2012-12-31,First Class,AH-100301406,Aaron Hawkins,Corporate,10035.0,New York City,...,2754.000,NaN,NaN,NaN,6.0,0.0,358.0200,752.47,Critical,0.130000

In [34]:
#Task 7

# Save the updated DataFrame to a new Excel file
df.to_excel("Cleaned_Global_Superstore.xlsx", index=False)
print("Updated dataset saved to 'Cleaned_Global_Superstore.xlsx'")

Updated dataset saved to 'Cleaned_Global_Superstore.xlsx'